# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteCatMoveCet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteCatMoveCet

 pod 'IHKeyboardAvoiding'
 pod 'Reusable'
 pod 'Alamofire', '5.0.0-beta.3'
 pod 'AlamofireObjectMapper'
 pod 'RealmSwift'
 pod 'SwiftyJSON'
 pod 'SwiftMessages' 
 pod 'SVProgressHUD'
 pod 'SpringIndicator'

end
